set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "" FORCE)
set(CMAKE_CACHEFILE_DIR "c:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/build-My setup 2" CACHE STRING "" FORCE)
set(CMAKE_CACHE_MAJOR_VERSION "3" CACHE STRING "" FORCE)
set(CMAKE_CACHE_MINOR_VERSION "30" CACHE STRING "" FORCE)
set(CMAKE_CACHE_PATCH_VERSION "5" CACHE STRING "" FORCE)
set(CMAKE_COMMAND "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/cmake.exe" CACHE STRING "" FORCE)
set(CMAKE_CPACK_COMMAND "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/cpack.exe" CACHE STRING "" FORCE)
set(CMAKE_CTEST_COMMAND "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/ctest.exe" CACHE STRING "" FORCE)
set(CMAKE_EDIT_COMMAND "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/cmake-gui.exe" CACHE STRING "" FORCE)
set(CMAKE_EXPORT_COMPILE_COMMANDS "1" CACHE STRING "" FORCE)
set(CMAKE_FIND_PACKAGE_REDIRECTS_DIR "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/build-My setup 2/CMakeFiles/pkgRedirects" CACHE STRING "" FORCE)
set(CMAKE_GENERATOR "Ninja" CACHE STRING "" FORCE)
set(CMAKE_HOME_DIRECTORY "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_BINDIR "bin" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_DATAROOTDIR "share" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_INCLUDEDIR "include" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_LIBDIR "lib" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_LIBEXECDIR "libexec" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_LOCALSTATEDIR "var" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_OLDINCLUDEDIR "/usr/include" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_PREFIX "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/install" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_SBINDIR "sbin" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_SHAREDSTATEDIR "com" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_SYSCONFDIR "etc" CACHE STRING "" FORCE)
set(CMAKE_MAKE_PROGRAM "C:/MikroElektronika/MikroElektronika/NECTOStudio/bin/ninja.exe" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/mikroc/pic/mikroc/mikroCPIC1618.exe" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_FORCED "TRUE" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_ID "mikroC" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_ID_RUN "TRUE" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_WORKS "TRUE" CACHE STRING "" FORCE)
set(CMAKE_NUMBER_OF_MAKEFILES "1" CACHE STRING "" FORCE)
set(CMAKE_PLATFORM_INFO_INITIALIZED "1" CACHE STRING "" FORCE)
set(CMAKE_PREFIX_PATH "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/install" CACHE STRING "" FORCE)
set(CMAKE_PROJECT_NAME "soundbuzzer" CACHE STRING "" FORCE)
set(CMAKE_ROOT "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/share/cmake-3.30" CACHE STRING "" FORCE)
set(CMAKE_SKIP_INSTALL_RPATH "NO" CACHE STRING "" FORCE)
set(CMAKE_SKIP_RPATH "NO" CACHE STRING "" FORCE)
set(CMAKE_TOOLCHAIN_FILE "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/build-My setup 2/toolchain.cmake" CACHE STRING "" FORCE)
set(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE STRING "" FORCE)
set(CMAKE_mikroC_COMPILER_WORKS "1" CACHE STRING "" FORCE)
set(CORE_LIB "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/lib/lib_core.a" CACHE STRING "" FORCE)
set(CORE_NAME "P18" CACHE STRING "" FORCE)
set(FIND_PACKAGE_MESSAGE_DETAILS_MikroC.Sound "["C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/cmake/../bin/P18/__Lib_Sound/__Lib_Sound.mcl"][v()]" CACHE STRING "" FORCE)
set(FIND_PACKAGE_MESSAGE_DETAILS_MikroC.System "["C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/cmake/../bin/P18/__Lib_System_000/MikroC.System.a"][v()]" CACHE STRING "" FORCE)
set(FLATTEN_ME "TRUE" CACHE STRING "" FORCE)
set(FLATTEN_ME_LEVEL "FLATTEN_ME_LEVEL_HIGH" CACHE STRING "" FORCE)
set(HAS_MIKROBUS "true" CACHE STRING "" FORCE)
set(IS_PD_SETUP "FALSE" CACHE STRING "" FORCE)
set(JCFG_FILE "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/PIC18F45K22.jcfg" CACHE STRING "" FORCE)
set(LEGACY_LIBRARIES ""C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/cmake/../bin/P18/__Lib_System_000/MikroC.System.a" "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/cmake/../bin/P18/__Lib_Sound/__Lib_Sound.mcl" "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/cmake/../bin/P18/__Lib_System_000/MikroC.System.a"" CACHE STRING "" FORCE)
set(LOG_INTERFACE "LOG_INTERFACE_STDOUT" CACHE STRING "" FORCE)
set(MCU_FLASH "32768" CACHE STRING "" FORCE)
set(MCU_IS_DUALCORE "0" CACHE STRING "" FORCE)
set(MCU_NAME "PIC18F45K22" CACHE STRING "" FORCE)
set(MCU_RAM "1536" CACHE STRING "" FORCE)
set(MIKROSDK_TYPE "legacy" CACHE STRING "" FORCE)
set(MSDK_BUILD_TFT_MODULES "FALSE" CACHE STRING "" FORCE)
set(MikroC.Core_DIR "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/lib/cmake/MikroC.Core" CACHE STRING "" FORCE)
set(NECTO_APPLICATION_DIR "C:/MikroElektronika/MikroElektronika/NECTOStudio/bin" CACHE STRING "" FORCE)
set(NECTO_DESIGNER_GENERATOR_PATH "C:/MikroElektronika/MikroElektronika/NECTOStudio/bin/vtft_generator.exe" CACHE STRING "" FORCE)
set(OSC "32" CACHE STRING "" FORCE)
set(PREINIT_ROUTINE_PATH "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/preinit" CACHE STRING "" FORCE)
set(PROJECT_TYPE "legacy" CACHE STRING "" FORCE)
set(SEARCH_PATHS "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/build-My setup 2;C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/core/PIC/mikroC/pic_mikroc_pic18/def;C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer" CACHE STRING "" FORCE)
set(TEST_LIB_PATH "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/unit_test_lib" CACHE STRING "" FORCE)
set(TOOLCHAIN_ID "mikrocpic" CACHE STRING "" FORCE)
set(TOOLCHAIN_LANGUAGE "MikroC" CACHE STRING "" FORCE)
set(XC8_SUPPORTED "TRUE" CACHE STRING "" FORCE)
set(_GNUInstallDirs_LAST_CMAKE_INSTALL_PREFIX "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/install" CACHE STRING "" FORCE)
set(_HAS_MIKROBUS_ "TRUE" CACHE STRING "" FORCE)
set(_MSDK_BOARD_NAME_ "BOARD_EASYPIC_V7" CACHE STRING "" FORCE)
set(_MSDK_DIP_SOCKET_TYPE_ "DIP40" CACHE STRING "" FORCE)
set(_MSDK_ETH_PHY_CHIP_ "NULL" CACHE STRING "" FORCE)
set(_MSDK_HAL_LOW_LEVEL_TARGET_ "mikroe" CACHE STRING "" FORCE)
set(_MSDK_PACKAGE_PIN_COUNT_ "40" CACHE STRING "" FORCE)
set(soundbuzzer_BINARY_DIR "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/build-My setup 2" CACHE STRING "" FORCE)
set(soundbuzzer_IS_TOP_LEVEL "ON" CACHE STRING "" FORCE)
set(soundbuzzer_SOURCE_DIR "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer" CACHE STRING "" FORCE)
set(TOOLCHAIN_ID "mikrocpic" CACHE STRING "" FORCE)
set(OSC "32" CACHE STRING "" FORCE)


set(COMPILER_FLAGS -C -MF -O11111114   "-DBG")
set(LINKER_FLAGS -C -MF -O11111114   "-DBG")

string(TOLOWER ${CMAKE_BUILD_TYPE} build_type)
if (build_type STREQUAL debug)
    list(APPEND COMPILER_FLAGS "-UICD")
    list(APPEND LINKER_FLAGS "-UICD")
endif()

file(TO_CMAKE_PATH "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/PIC18F45K22.jcfg" JCFG_FILE_VAL)
set(JCFG_FILE  ${JCFG_FILE_VAL} CACHE STRING "" FORCE)

file(TO_CMAKE_PATH "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/lib/lib_core.a" CORE_LIB_VAL)
set(CORE_LIB ${CORE_LIB_VAL} CACHE STRING "" FORCE)

set(SEARCH_PATHS "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/build-My setup 2;C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/core/PIC/mikroC/pic_mikroc_pic18/def;C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer" CACHE STRING "" FORCE)

set(CMAKE_MikroC_COMPILER "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/mikroc/pic/mikroc/mikroCPIC1618.exe" CACHE INTERNAL "")
set(CMAKE_MikroC_COMPILER_ID "mikroC" CACHE INTERNAL "")

set(CMAKE_MikroC_OUTPUT_EXTENSION_REPLACE 1)
set(CMAKE_MikroC_OUTPUT_EXTENSION ".mcl")

# set CMAKE_SYSTEM_NAME to define build as CMAKE_CROSSCOMPILING
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_MikroC_COMPILER_WORKS TRUE CACHE INTERNAL "")
SET(CMAKE_MikroC_COMPILER_FORCED TRUE CACHE INTERNAL "")
SET(CMAKE_MikroC_COMPILER_ID_RUN TRUE CACHE INTERNAL "")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# add compiler option flags
add_compile_options(${COMPILER_FLAGS})
message(INFO ": ${COMPILER_FLAGS}")
# add link option flags
add_link_options(${LINKER_FLAGS})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

file(TO_CMAKE_PATH "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/lib/cmake" MIKROSDK_PATH)
file(TO_CMAKE_PATH "C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/lib/cmake" MIKROC_CORE_PATH)


set(MIKROSDK_ROOT_PATH ${MIKROSDK_PATH})
set(MIKROC_CORE_ROOT_PATH ${MIKROC_CORE_PATH})
#append to cmake_prefix_path
list(APPEND CMAKE_PREFIX_PATH ${MIKROSDK_ROOT_PATH})
list(APPEND CMAKE_PREFIX_PATH ${MIKROC_CORE_ROOT_PATH})

list(APPEND CMAKE_MODULE_PATH "C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/cmake;C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/core/PIC/mikroC/pic_mikroc_pic18/cmake;C:/Users/796324/AppData/Local/MIKROE/NECTOStudio7/packages/mikroe_utils_common;C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/lib/cmake;C:/Users/796324/OneDrive - hull.ac.uk/GitHub/Embedded-systems-/soundbuzzer/.meproject/setup/Debug/cmake")


